name: Docker Build & Push to Docker Hub

on:
  push:
    branches:
      - dev
      - main
    paths:
      - 'projects/01-flask-docker-ci/**'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub (only on main)
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t iam-demo ./projects/01-flask-docker-ci

      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag iam-demo docker.io/${{ secrets.DOCKERHUB_USERNAME }}/iam-demo:latest
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/iam-demo:latest
